require("scripts.atmosphere")
require("scripts.charging-rod")
require("scripts.cooling")
require("scripts.crusher")
require("scripts.cryogenic-plant")
require("scripts.events")
require("scripts.ice")
require("scripts.init")
require("scripts.lighting")
require("scripts.nuclear-reactor")
require("scripts.radiative-tower")
require("scripts.reactor-repair")
require("scripts.teleporter")
require("scripts.terrain")

if script.active_mods["gvv"] then require("__gvv__.gvv")() end