require("prototypes.override-final.entity")
require("prototypes.override-final.item")
require("prototypes.override-final.recipe")
require("prototypes.override-final.lab")
require("prototypes.override-final.technology")

require("compat.categories")
require("compat.compat")
require("compat.5-dim")
require("compat.any-planet-start")
require("compat.maraxsis")
require("compat.static-recycling")
