require("compat.autoban")
require("prototypes.override-final.entity")
require("prototypes.override-final.item")
require("prototypes.override-final.hidden")
require("prototypes.override-final.recipe")
require("prototypes.override-final.technology")

require("compat.compat")
require("compat.static-recycling")
require("compat.any-planet-start")
require("compat.categories")
require("compat.maraxsis")
require("compat.mulana")
require("compat.plutonium-energy")
require("compat.krastorio-2")
