data:extend({
	{
		type = "bool-setting",
		name = "cerys-disable-flare-stack-item-venting",
		setting_type = "startup",
		default_value = true,
		order = "a",
	},
	{
		type = "bool-setting",
		name = "cerys-enforce-vanilla-recycling-recipes",
		setting_type = "startup",
		default_value = true,
		order = "b",
	},
	{
		type = "double-setting",
		name = "cerys-undo-marathon-multiplier",
		setting_type = "startup",
		default_value = 1.0,
		minimum_value = 0.1,
		maximum_value = 100000.0,
		order = "c",
	},
	{
		type = "bool-setting",
		name = "cerys-radiative-heaters-require-cryogenic-science",
		setting_type = "startup",
		default_value = true,
		order = "d",
	},
	{
		type = "bool-setting",
		name = "cerys-use-fulgora-starmap-graphic",
		setting_type = "startup",
		default_value = false,
		order = "f",
	},
	{
		type = "bool-setting",
		name = "cerys-sandbox-mode",
		setting_type = "startup",
		default_value = false,
		order = "g",
	},
	{
		type = "bool-setting",
		name = "cerys-disable-secret-cell-productivity-tech-for-legacy-saves",
		setting_type = "startup",
		default_value = false,
		order = "z",
	},
	{
		type = "bool-setting",
		name = "cerys-dynamic-lighting",
		setting_type = "runtime-global",
		default_value = true,
		order = "a",
	},
	{
		type = "bool-setting",
		name = "cerys-asteroid-chunks-drop-on-belts",
		setting_type = "runtime-global",
		default_value = true,
		order = "b",
	},
	{
		type = "bool-setting",
		name = "cerys-disable-solar-wind-when-not-looking-at-surface",
		setting_type = "runtime-global",
		default_value = false,
		order = "d",
	},
	{
		type = "double-setting",
		name = "cerys-solar-wind-spawn-rate-percentage",
		setting_type = "runtime-global",
		default_value = 100.0,
		minimum_value = 0.0,
		maximum_value = 200.0,
		order = "f",
	},
	{
		type = "double-setting",
		name = "cerys-plutonium-generation-rate-multiplier",
		setting_type = "runtime-global",
		default_value = 1.0,
		minimum_value = 0.1,
		maximum_value = 1000.0,
		order = "g",
	},
	{
		type = "bool-setting",
		name = "cerys-disable-parallax-in-multiplayer",
		setting_type = "runtime-global",
		default_value = true,
		order = "h",
	},
	{
		type = "bool-setting",
		name = "cerys-disable-kofi-toast",
		setting_type = "runtime-global",
		default_value = false,
		order = "z",
	},
})

data:extend({
	{
		type = "bool-setting",
		setting_type = "startup",
		name = "cerys-hardcore-mode",
		forced_value = false,
		default_value = false,
		hidden = true,
	},
})
