data:extend({
	{
		type = "sprite",
		name = "fulgora-background",
		filename = "__Cerys-Moon-of-Fulgora__/graphics/sharper-planets/fulgora.png",
		priority = "extra-high-no-scale",
		width = 2048,
		height = 2048,
		flags = { "no-crop" },
		mipmap_count = 1,
		scale = 4,
	},
	{
		type = "sprite",
		name = "radiative-tower-base-ice",
		filename = "__Cerys-Moon-of-Fulgora__/graphics/entity/radiative-tower/back-ice.png",
		priority = "extra-high",
		width = 988,
		height = 962,
		shift = util.by_pixel(58, -38),
		mipmap_count = 1,
		scale = 0.22,
	},
	{
		type = "sprite",
		name = "radiative-tower-tower-shadow-1",
		filename = "__Cerys-Moon-of-Fulgora__/graphics/entity/radiative-tower/tower-shadow-1.png",
		width = 988,
		height = 962,
		shift = util.by_pixel(58, -38),
		mipmap_count = 1,
		scale = 0.22,
		draw_as_shadow = true,
	},
	{
		type = "sprite",
		name = "radiative-tower-tower-shadow-2",
		filename = "__Cerys-Moon-of-Fulgora__/graphics/entity/radiative-tower/tower-shadow-2.png",
		width = 988,
		height = 962,
		shift = util.by_pixel(58, -38),
		mipmap_count = 1,
		scale = 0.22,
		draw_as_shadow = true,
	},
	{
		type = "sprite",
		name = "cerys-charging-rod-red-light",
		filename = "__Cerys-Moon-of-Fulgora__/graphics/entity/charging-rod/red-light.png",
		width = 108,
		height = 352,
		shift = util.by_pixel(0, -85.0),
		mipmap_count = 1,
		scale = 0.75,
	},
})
