data:extend({
	{
		type = "proxy-container",
		name = "cerys-proxy-pickup",
		flags = {
			"not-repairable",
			"not-on-map",
			"not-deconstructable",
			"not-blueprintable",
			"not-selectable-in-game",
			"not-upgradable",
			"not-in-kill-statistics",
			"no-automated-item-insertion",
		},
		max_health = 1e9,
		picture = util.empty_sprite(),
		draw_inventory_content = false,
		draw_copper_wires = false,
		draw_circuit_wires = false,
		create_ghost_on_death = false,
		created_smoke = nil,
		collision_box = { { -0.0, -0.0 }, { 0.0, 0.0 } },
		selection_box = { { -0.0, -0.0 }, { 0.0, 0.0 } },
		collision_mask = { layers = {}, not_colliding_with_itself = true },
		remove_decoratives = "false",
		selectable_in_game = false,
		tile_height = 1,
		tile_width = 1,
		selection_priority = 0,
		hidden = true,
		hidden_in_factoriopedia = true,
	},
	{
		type = "proxy-container",
		name = "cerys-proxy-drop",
		flags = {
			"not-repairable",
			"not-on-map",
			"not-deconstructable",
			"not-blueprintable",
			"not-selectable-in-game",
			"not-upgradable",
			"not-in-kill-statistics",
			"no-automated-item-removal",
			"no-automated-item-insertion",
		},
		max_health = 1e9,
		picture = util.empty_sprite(),
		draw_inventory_content = false,
		draw_copper_wires = false,
		draw_circuit_wires = false,
		create_ghost_on_death = false,
		created_smoke = nil,
		collision_box = { { -0.0, -0.0 }, { 0.0, 0.0 } },
		selection_box = { { -0.0, -0.0 }, { 0.0, 0.0 } },
		collision_mask = { layers = {}, not_colliding_with_itself = true },
		remove_decoratives = "false",
		selectable_in_game = false,
		tile_height = 1,
		tile_width = 1,
		selection_priority = 0,
		hidden = true,
		hidden_in_factoriopedia = true,
	},
})
