data.raw.recipe["superconductor"].category = "electromagnetics-or-fulgoran-cryogenics"
data.raw.recipe["sulfuric-acid"].category = "chemistry-or-cryogenics-or-fulgoran-cryogenics"
data.raw.recipe["plastic-bar"].category = "chemistry-or-cryogenics-or-fulgoran-cryogenics"
data.raw.recipe["lithium"].category = "chemistry-or-cryogenics-or-fulgoran-cryogenics"
data.raw.recipe["battery"].category = "chemistry-or-cryogenics-or-fulgoran-cryogenics"
data.raw.recipe["ammonia-rocket-fuel"].category = "chemistry-or-cryogenics-or-fulgoran-cryogenics"
